# Array

In [12]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)
print(type(x))
print(x.ndim) #it will show up the dimension of arary


[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [10]:
l=[]
for i in range(1,5):
    int_l = int(input("Enter the number:"))
    l.append(int_l)
print(np.array(l))

Enter the number: 12
Enter the number: 34
Enter the number: 24
Enter the number: 22


[12 34 24 22]


In [13]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [14]:
ar3=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [15]:
arn=np.array([1,2,3,4],ndmin=10)
#ndmin is the short cut to create n dimensional array
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


To create special type of array
1. To create array with only 0 element use
   np.zeros(4)-> for 1 dimensional
   np.zeros([3,4])->for 2 dimensional
2. To creaye array with only 1 elements use
   np.ones(4)

# Array with Random numbers

# Rand()

In [16]:
var = np.random.rand(4)
print(var)

[0.81717218 0.83264102 0.42939004 0.39033227]


In [18]:
var1 = np.random.rand(4,5)
print(var1)

[[0.47069961 0.38328893 0.94691455 0.73667796 0.48075356]
 [0.94005708 0.15414777 0.4170127  0.96734628 0.51198899]
 [0.23241427 0.84115504 0.68158374 0.11624951 0.90818784]
 [0.52355436 0.21291449 0.74702505 0.61219734 0.17926928]]


# randn()

Generate random value close to zero. This may return positive or negative number as well

# ranf()

The function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floast in the half-open interval [0.0,1.0]

# randint()

The function is used to generate a random number between a given range. 
var4 = np.random.randint(min,max,total_number_you_want)

In [20]:
var4 = np.random.randint(5,20,5)
print(var4)

[13 16 10 13  9]


# Numpy data types

In [3]:
import numpy as np
var6= np.array([1,2,3,4])
print("Data type:",var6.dtype)

Data type: int32


In [4]:
var7= np.array([1.0,2.1,3.3,4.4])
print("Data type:",var7.dtype)

Data type: float64


In [7]:
var8= np.array(["A","B","C","D",1,2])
print("Data type:",var8.dtype)

Data type: <U11


In [9]:
x= np.array([1,2,3,4],dtype=np.int8) #changing the data type syntax
print("Data type:",x.dtype)

Data type: int8


In [11]:
x1= np.array([1,2,3,4],dtype="f") #changing the data type syntax using shortcut
print("Data type:",x1.dtype)
print(x)

Data type: float32
[1 2 3 4]


In [13]:
x2= np.array([1,2,3,4],dtype=np.int8) #changing the data type as a function
new=np.float32(x2)
print("Data type:",x2.dtype)
print("Data type:",new.dtype)
print(x)
print(new)

Data type: int8
Data type: float32
[1 2 3 4]
[1. 2. 3. 4.]


In [16]:
x3= np.array([1,2,3,4]) #changing the data type syntax using astype function
new_1=x3.astype(float)
print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


# Shape and Reshapping

In [17]:
x4 = np.array([[1,2,3,4],[1,2,3,4]])
print(x4)
print()
print(x4.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [19]:
x5=np.array([1,2,3,4],ndmin=4)
print(x5)
print(x5.ndim)
print()
print(x5.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


# Reshape

In [24]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print (var2.ndim)
print()
x = var2.reshape (3,2)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [27]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()
x1 = var3.reshape (2,3,2)
print(x1)
print (x1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [30]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print (var3)
print(var3.ndim)
print ()
x1 = var3.reshape (2,3,2)
print (x1)
print (x1.ndim)
print ()
one =x1.reshape (-1) #$this will create one dimensional array
print (one)
print (one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


# Airthmetic operation 

In [32]:
var1= np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = np.add(var1, var2) #similar for sub divide mod and multiply
print(varadd)

[2 4 6 8]


np.add(a,b)
np.subtract(a,b)
np.multiply(a,b)
np.divide(a,b)
np.mod(a,b)
np.power(a,b)
np.reciprocal(a)

np.min(x)
np.max(x )
np.argmin(x)
np.sqrt(x)
np.sin(x)
np.cos(x)
np.cumsum( x )

In [34]:
var1= np.array([[2,1,3], [9,5,6]])
print(np.min(var1, axis=0))

[2 1 3]


# Broadcasting

In [37]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
print( var1 + var2 ) 

[2 4 6 8]


In [40]:
var1 = np.array([1,2,3])
print(var1.shape)
print()
print(var1)
print()
var2 = np.array([[1], [2], [3]])
print(var2.shape)
print()
print(var2)
print()
print(var1*var2)

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

[[1 2 3]
 [2 4 6]
 [3 6 9]]


# Indexing

In [42]:
var =np.array([1,2,3,4])
print(var[1])
print(var[-1])

2
4


In [43]:
var1 = np.array([[9,8,7], [4,5,6]])
print(var1)
print(var1.ndim)
print()
print(var1[0,2])

[[9 8 7]
 [4 5 6]]
2

7


In [44]:
var2 =np.array([[[1,2], [6,7]]])
print(var2)
print(var2.ndim)
print()
print (var2[0,1,1])

[[[1 2]
  [6 7]]]
3

7


# Slicing

In [55]:
var = np.array([9,2,8,4,0,3,1])
print(var)
print()
print("2 to 0:", var[1:5])
print("2 to End", var[1:])
print("start to 0", var[:5])
print("step:",var[1:6:2])

[9 2 8 4 0 3 1]

2 to 0: [2 8 4 0]
2 to End [2 8 4 0 3 1]
start to 0 [9 2 8 4 0]
step: [2 4 3]


In [56]:
var1 = np.array([[1,2,3,4,5],[9,8,17,6,5],[11,12,13,14,15]])
print(var1)
print()
print("8 to 5: ", var1[1,1:])

[[ 1  2  3  4  5]
 [ 9  8 17  6  5]
 [11 12 13 14 15]]

8 to 5:  [ 8 17  6  5]


 # Iteration Numpy array

In [58]:
var = np.array([9,8,7,6,5,4])
print(var)
print()
for i in var:
    print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


In [61]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
for j in var1:
    print(j)
print()
for k in var1:
    for l in k:
        print(l)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [62]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()
for i in np.nditer(var3): #np.nditer avoid the multiple use of for loop
    print(i)

[[[9 8 7 6]
  [1 2 3 4]]]
3

9
8
7
6
1
2
3
4


In [63]:
var4 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var4)
print(var4.ndim)
print()
for i,d in np.ndenumerate(var4): #np.denumerate iterate the data with index
    print(i,d)

[[[9 8 7 6]
  [1 2 3 4]]]
3

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


# copy vs view

In [64]:
var = np.array([1,2,3,4])
co = var.copy ()
print("var:" , var)
print("copy : ", co)


var: [1 2 3 4]
copy :  [1 2 3 4]


In [65]:
x = np.array([9,8,7,6,5])
vi = x.view()
print("x",x)
print("view :",vi)

x [9 8 7 6 5]
view : [9 8 7 6 5]


 # Join Array

In [68]:
var=np.array([1,2,3,4])
var1=np.array([9,8,7,6])
ar=np.concatenate((var,var1))
print(ar)

[1 2 3 4 9 8 7 6]


In [71]:
vr=np.array([[1,2],[3,4]])
vr1=np.array([[9,8],[7,6]])
ar1=np.concatenate((vr,vr1),axis=1)
print(ar1) 

[[1 2 9 8]
 [3 4 7 6]]


In [75]:
var_1=np.array([1,2,3,4])
var_2=np.array([9,8,7,6])
ar_new=np.stack((var_1,var_2),axis=1)#stack will join array through axis
ar_new1=np.hstack((var_1,var_2))#row
ar_new2=np.stack((var_1,var_2)) #column
ar_new3=np.dstack((var_1,var_2)) #height
print(ar_new)
print()
print(ar_new1)
print()
print(ar_new2)
print()
print(ar_new3)
print()

[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]



# split array

In [77]:
var=np.array([1,2,3,4,5,6])
print(var)
ar=np.array_split(var,3)
print(ar)
print(ar[0])

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


In [80]:
var1=np.array([[1,2],[3,4],[5,6]])
print(var1)
ar1=np.array_split(var1,3)
print(ar1)
print()
ar2=np.array_split(var1,3,axis=1)
print(ar2)

[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]


# Search

In [84]:
var = np.array([1,2,3,2,4,2,5,6,7,8])
x=np.where((var%2)==0)
print(x)

(array([1, 3, 4, 5, 7, 9], dtype=int64),)


var1 = np.array([1,2,3,4,6,7,8,9])
x1=np.searchsorted(var1,5)
print(x1)

# sort

In [87]:
var2 = np.array([72,5,67,45,78,33,45,778])
x2=np.sort(var2)
print(x2)

[  5  33  45  45  67  72  78 778]


# Filter array

In [89]:
var_3=np.array([1,2,3,4,5])
f=[True,False,True,False,False]
new_a=var_3[f]
print(new_a)

[1 3]


# Arithmetic function

In [92]:
var_4=np.array([1,2,3,4,5])
np.random.shuffle(var_4)
print(var_4)

[2 4 5 1 3]


In [94]:
var1=np.array([1,2,3,4,2,5,6,7,2])
x=np.unique(var1, return_index=True, return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 6, 7], dtype=int64), array([1, 3, 1, 1, 1, 1, 1], dtype=int64))


In [101]:
var_6=np.array([1,2,3,4,5])
y=np.resize(var_6,(2,3))
print(y)
print()
print(y.flatten())
print("Flatten:", y.flatten(order="F"))
print("Ravel:",np.ravel(y,order="A"))

[[1 2 3]
 [4 5 1]]

[1 2 3 4 5 1]
Flatten: [1 4 2 5 3 1]
Ravel: [1 2 3 4 5 1]


# Insert

In [102]:
var_7=np.array([1,2,3,4,5])
print(var_7)
v=np.insert(var_7, 2, 40)
print(v)

[1 2 3 4 5]
[ 1  2 40  3  4  5]


In [105]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
v1=np.insert(ar2, 2, 40, axis=1)
print(v1)

[[ 1  2 40  3  4]
 [ 1  2 40  3  4]]


# Delete

In [106]:
var_8=np.array([1,2,30,4,5])
print(var_8)
v3=np.delete(var_8, 2)
print(v3)

[ 1  2 30  4  5]
[1 2 4 5]


# Matrix

In [109]:
ar1 = np.matrix([[1,2],[1,2]])
ar2 = np.matrix([[1,2],[1,2]])
print(ar1)
print(type(ar1))
print(ar1.dot(ar2))

[[1 2]
 [1 2]]
<class 'numpy.matrix'>
[[3 6]
 [3 6]]


In [108]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(type(ar2))

[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
